version: '3.8'

services:
  node_app:
    build:
      context: ./
      target: production
    container_name: node_app
    restart: always
    working_dir: /app
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "127.0.0.1:3002:3002"
    environment:
      NODE_ENV: ${NODE_ENV}
      DEBUG: nodejs-docker-express:*
    networks:
      - nginxproxy_default
      - internal

    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal

volumes:
  mariadb_data:
networks:
  nginxproxy_default:
    external: true
  internal:
